apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wine-separate-3-deployment
  labels:
    app: wine-separate-3
spec:
  replicas: 1
  selector:
    matchLabels:
        app: wine-separate-3
  template:
    metadata:
      labels:
        app: wine-separate-3
    spec:
      securityContext:
        fsGroup: 1010
      containers:
      - name: solarkennedy-wine-x11-novnc-docker
        image: launchthatbrand/solarkennedy-wine-x11-novnc-docker:release-1.0.6
        securityContext:
          runAsUser: 0
      - name: nevmerzhitsky-headless-metatrader4
        image: launchthatbrand/nevmerzhitsky-headless-metatrader4:elease-1.0.10
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
        # need poststart to copy files from DockerFile path into pvc path. cant run chmod here as it needs root.
        lifecycle:
          postStart:
            exec:
              command: 
                - "/bin/sh"
                - "-c"
                - >
                  if [ ! -f /home/winer/.wine/drive_c/mt4/terminal.exe ]; then
                  mkdir -p /home/winer/.wine/drive_c/mt4;
                  cp -R /home/winer/.cache/mt4_kot4x/* /home/winer/.wine/drive_c/mt4/;
                  fi;
                  if [ ! -f /home/winer/.wine/drive_c/windows/Fonts/wingding.ttf ]; then
                  mkdir -p /home/winer/.wine/drive_c/windows/Fonts;
                  cp -R /home/winer/.cache/fonts/* /home/winer/.wine/drive_c/windows/Fonts;
                  fi;
        volumeMounts:
        - name: wine-separate-3-volume
          mountPath: /home/winer/.wine/
      initContainers:
      # need init container to run chown command as root. Cant use postStart as then everything would need to run as root.
      - name: init-myservice
        image: busybox
        command: ['sh', '-c', 'chown -R 1000:1010 /home/winer/; echo The app is running!']
        #command: ['sh', '-c', 'while true; do sleep 30; done;']
        volumeMounts:
        - name: wine-separate-3-volume
          mountPath: /home/winer/.wine/
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: wine-separate-3-volume
        persistentVolumeClaim:
          claimName: wine-separate-3-pvc
        