apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wine-separate-2-deployment
  labels:
    app: wine-separate-2
spec:
  replicas: 1
  selector:
    matchLabels:
        app: wine-separate-2
  template:
    metadata:
      labels:
        app: wine-separate-2
    spec:
      securityContext:
        fsGroup: 1010
      containers:
      - name: solarkennedy-wine-x11-novnc-docker
        image: launchthatbrand/solarkennedy-wine-x11-novnc-docker:latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
      - name: nevmerzhitsky-headless-metatrader4
        image: launchthatbrand/nevmerzhitsky-headless-metatrader4:minimal
        imagePullPolicy: Always
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "chown winer:winer -R /home/winer/.wine; cp -R /home/winer/.cache/mt4_kot4x/* /home/winer/.wine/drive_c/mt4"]
        volumeMounts:
        - name: wine-separate-2-volume
          mountPath: /home/winer/.wine/drive_c/mt4
      #initContainers:
      #- name: init-myservice
      #  image: busybox
      #  command: ['sh', '-c', 'echo The app is running! && sleep 36000']
          #- chown
          #- -R
          #- 1000:1010
          #- /home/winer/.wine/
        #volumeMounts:
        #- name: wine-separate-2-volume
        #  mountPath: /home
      volumes:
      - name: wine-separate-2-volume
        persistentVolumeClaim:
          claimName: wine-separate-2-pvc
        