apiVersion: v1 
kind: Service
metadata:
  name: "$Username-$brand-$product-$random-$i"
  labels:
    user: "$Username"
    client: "$brand"
    app: "$product"
    id: "$random-$i"
spec:
  ports:
  #- port: 8080
  #  protocol: TCP
  #  name: "$Username-$random-novnc"
  - port: 5900
    protocol: TCP
    name: "$Username-$random-vnc"
    # nodePort : 30380
  selector:
    user: "$Username"
    client: "$brand"
    app: "$product"
    id: "$random-$i"
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "$Username-$brand-$product-$random-$i"
  labels:
    user: "$Username"
    client: "$brand"
    app: "$product"
    id: "$random-$i"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
        