apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wine-separate-2-deployment
  labels:
    app: wine-separate-2
spec:
  replicas: 1
  selector:
    matchLabels:
        app: wine-separate-2
  template:
    metadata:
      labels:
        app: wine-separate-2
    spec:
      securityContext:
        fsGroup: 1010
      containers:
      - name: solarkennedy-wine-x11-novnc-docker
        image: launchthatbrand/solarkennedy-wine-x11-novnc-docker:latest
        securityContext:
          runAsUser: 0
      - name: nevmerzhitsky-headless-metatrader4
        image: launchthatbrand/nevmerzhitsky-headless-metatrader4:elease-1.0.5
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
        # need poststart to copy files from DockerFile path into pvc path. cant run chmod here as this it needs root.
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "cp -R /home/winer/.cache/mt4_kot4x/* /home/winer/.wine/drive_c/mt4/"]
        volumeMounts:
        - name: wine-separate-2-volume
          mountPath: /home/winer/.wine/drive_c/mt4
      initContainers:
      # need init container to run chown command as root. Cant use postStart as then everything would need to run as root.
      - name: init-myservice
        image: busybox
        command: ['sh', '-c', 'chown -R 1000:1010 /home/winer/.wine; echo The app is running!']
        volumeMounts:
        - name: wine-separate-2-volume
          mountPath: /home/winer/.wine/drive_c/mt4
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: wine-separate-2-volume
        persistentVolumeClaim:
          claimName: wine-separate-2-pvc
        