apiVersion: v1 
kind: Service
metadata:
  name: wine-separate-2-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: wine-separate-2-novnc
  selector:
    app: wine-separate-2
  type: NodePort
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wine-separate-2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: wine-separate-2
  template:
    metadata:
      labels:
        app: wine-separate-2
    spec:
      containers:
      - name: solarkennedy-wine-x11-novnc-docker
        image: solarkennedy/wine-x11-novnc-docker
        ports:
        - containerPort: 8080
      - name: nevmerzhitsky-headless-metatrader4
        image: launchthatbrand/nevmerzhitsky-headless-metatrader4:minimal
        ports:
        - containerPort: 6000
